//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourceProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes
    {
        public int Id { get; set; }
        public string UserLogin { get; set; }
        public System.DateTime NoteDate { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
